In [6]:
import numpy as np

In [7]:
# 设置随机种子（可选）用于复现结果
np.random.seed(0)

# 初始化两个16x16的整数矩阵，值的范围在[-10, 10] （为了方便肉眼dubug）
matrix_A = np.random.randint(-10, 11, size=(16, 16))
matrix_B = np.random.randint(-10, 11, size=(16, 16))
# matrix_A = np.zeros((16, 16), dtype=np.int32)
# matrix_B = np.zeros((16, 16), dtype=np.int32)
# matrix_A[0][0] = -4;
# matrix_A[0][1] = 2;
# matrix_B[0][0] = 1;
# matrix_B[0][1] = 15;

# 计算两个矩阵的乘积
product_matrix = np.dot(matrix_A, matrix_B)
# relu
product_matrix[product_matrix < 0] = 0

# 将两个矩阵的值按照16进制存入对应文件
def save_to_hex_file(matrix, filename):
    with open(filename, 'w') as file:
        for row in matrix:
            for value in row:
                # 将数字转换为16进制，并去掉"0x"前缀，同时保证负号的正确表示
                hex_value = format(value if value >= 0 else value & 0xFFFFFFFF, '08x')
                file.write(hex_value + '\n')

save_to_hex_file(matrix_A, 'input_A.hex')
save_to_hex_file(matrix_B, 'input_B.hex')

# 输出乘积矩阵，检查结果（可选）
print('Matrix A:\n', matrix_A)
print('Matrix B:\n', matrix_B)
print('Product of matrix A and B:\n', product_matrix)


Matrix A:
 [[  2   5 -10  -7  -7  -3  -1   9   8  -6  -4   2  -9  -4  -3   4]
 [  7  -5   3  -2  -1  10   9   6   9  -5   5   5 -10   8  -7   7]
 [  9   9   9   4  -3 -10  -9  -1 -10   0  10  -7   1   8  -8 -10]
 [-10  -6  -5  -4  -2  10   7   5  -6  -1   0  -9  -9  -3  -1  -7]
 [ -4   1   4   8 -10   4  -7   2   0  10   1  -6  -4  -6   5  10]
 [ -7   2  -6  10  -2   4   5  10  -7   5   3   6   7  -5  -1  -7]
 [-10  -5 -10   7   8  -6  -8   6  -7  -8   0   3   6  -3  -1 -10]
 [  0   8   1  -8  -8  -7  -7   8   4  -7  10   7   8   4  -1  -9]
 [ -6   0   1  -2   1  -8   9   6 -10 -10  -4   9   4   0   9  -2]
 [  3  -8  -7  -8   1   3   6  -2  -2   9  -2  -8  10  -7   2   4]
 [-10  -6  -7   3   1   3   3   1   6   4   6   9  -9  -2 -10  -6]
 [ -4   3  -3   5  -1   8  -2   5   1  -4   5  -9   2  -7   8   5]
 [ -7   0   2  -4  -7  -5   1 -10   1  -2  10   0   1  -5   5  -2]
 [ -8   9   9   4  10  -7  -7  -3  -1  -1  -1  -7   4   8   2  -7]
 [ -1   0   3  -3  -3  -9   2  -8  -8  -9  -5  -2  

In [8]:
def change_file(file_name):
    '''
    每行作为一个32位整数读入，最终将256个数字变为16*16的矩阵输出
    '''
    with open(file_name, 'r') as file:
        lines = file.readlines()
        lines = [int(line.strip()) for line in lines]
        matrix = np.array(lines).reshape((16, 16))
        return matrix

In [10]:
def check():
    gpu_result = change_file('result.txt')

    # 判断结果是否正确
    if np.allclose(product_matrix, gpu_result):
        print('Correct!')

In [11]:
check()

Correct!
